CREATE TABLE IF NOT EXISTS payments (
  id CHAR(36) PRIMARY KEY, order_id CHAR(36) NOT NULL UNIQUE, customer_id CHAR(36) NOT NULL,
  amount DECIMAL(10,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'NAD', method VARCHAR(40) NOT NULL,
  status VARCHAR(16) NOT NULL, failure_reason VARCHAR(255) NULL, order_cancelled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE TABLE IF NOT EXISTS payment_transactions (
  id CHAR(36) PRIMARY KEY, payment_id CHAR(36) NOT NULL, type VARCHAR(16) NOT NULL,
  amount DECIMAL(10,2) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX ix_transactions_payment (payment_id)
);
